# Run tests against supported Node versions

version: 2.1

orbs:
  node: circleci/node@3.0.0

executors:
  node16:
    docker:
      - image: circleci/node:16.1.0
    working_directory: ~/workspace
  node14:
    docker:
      - image: circleci/node:14
    working_directory: ~/workspace
  node12_latest:
    docker:
    - image: circleci/node:12
    working_directory: ~/workspace
  node12_0:
    docker:
    - image: circleci/node:12.0
    working_directory: ~/workspace
  node12_17:
    docker:
    - image: circleci/node:12.17
    working_directory: ~/workspace
  node12_16:
    docker:
    - image: circleci/node:12.16
    working_directory: ~/workspace
  node10:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace

jobs:
  build_and_test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  push: &push_workflow
    jobs:
      - build_and_test:
          executor: node16
          name: node_16
      - build_and_test:
          executor: node14
          name: node_14
      - build_and_test:
          executor: node12_latest
          name: node_12_latest
      - build_and_test:
          executor: node12_0
          name: node_12_0
      # 12.16 is the last version without good-enough ES module support
      - build_and_test:
          executor: node12_16
          name: node_12_16
      # 12.16 is the first version with good-enough ES module support
      - build_and_test:
          executor: node12_17
          name: node_12_17
      - build_and_test:
          executor: node10
          name: node_10
  cron:
    <<: *push_workflow
    triggers:
      - schedule:
          # Times are UTC.
          cron: "0 10 * * *"
          filters:
            branches:
               only:
                 - main
                 - "3.99"
                 - "4.0"
