# Run tests against supported Node versions

version: 2.1

orbs:
  node: circleci/node@3.0.0
  win: circleci/windows@2.2.0

executors:
  node14:
    docker:
      - image: circleci/node:14
    working_directory: ~/workspace
  node12:
    docker:
      - image: circleci/node:12
    working_directory: ~/workspace
  node10:
    docker:
      - image: circleci/node:10
    working_directory: ~/workspace

jobs:
  build_and_test:
    parameters:
      executor:
        type: executor
    executor: << parameters.executor >>
    steps:
      - checkout
      - run:
          name: Report Node and NPM versions
          command: echo "Using Node $(node --version) and NPM $(npm --version)"
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm test

workflows:
  version: 2
  push: &push_workflow
    jobs:
      - build_and_test:
          executor: node14
          name: node_14
      - build_and_test:
          executor: node12
          name: node_12
      - build_and_test:
          executor: node10
          name: node_10
      - build_and_test:
          executor:
            name: win/default
            shell: powershell.exe
          name: node_12_windows
  cron:
    <<: *push_workflow
    triggers:
      - schedule:
          # Times are UTC.
          cron: "0 10 * * *"
          filters:
            branches:
               only:
                 - main
                 - "3.99"
                 - "4.0"
